services:
  medminer-cli:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MEDMINER_MODEL__MODEL_PROVIDER: "openai"
      MEDMINER_MODEL__MODEL: ""
      MEDMINER_MODEL__API_KEY: ""
      MEDMINER_MODEL__BASE_URL: ""
      MEDMINER_ICD_CLIENT_ID: ""
      MEDMINER_ICD_CLIENT_SECRET: ""
      MEDMINER_SNOMED_BASE_URL: "snowstorm:8080/MAIN"
      MEDMINER_WORKFLOW: ""
    volumes:
      - ./data/pre_medications:/app/data
      - ./data/snomed:/opt/snomed-data
    networks:
      - medminer-network
    depends_on:
      snowstorm-es:
        condition: service_healthy

  snowstorm-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: snowstorm-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    # volumes:
    #   - elastic-data:/usr/share/elasticsearch/data
    networks:
      medminer-network:
        aliases:
         - es
    healthcheck:
      test: ["CMD", "curl", "-f", "http://es:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    ports:
      - 127.0.0.1:9200:9200
    mem_reservation: 4g
    logging:
      driver: "none"

  snowstorm-srv:
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm-srv
    restart: always
    depends_on:
      snowstorm-es:
        condition: service_healthy
    entrypoint: java -Xms2g -Xmx4g --add-opens java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -cp @/app/jib-classpath-file org.snomed.snowstorm.SnowstormApplication --elasticsearch.urls=http://es:9200
    networks:
      medminer-network:
        aliases:
         - snowstorm
    ports:
      - 8080:8080
    logging:
      driver: "none"

networks:
  medminer-network:

volumes:
  elastic-data:
