services:
  medminer-cli:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MEDMINER_MODEL__MODEL_PROVIDER: "openai"
      MEDMINER_MODEL__MODEL: ""
      MEDMINER_MODEL__API_KEY: ""
      MEDMINER_MODEL__BASE_URL: ""
      MEDMINER_ICD_CLIENT_ID: ""
      MEDMINER_ICD_CLIENT_SECRET: "="
      MEDMINER_SNOMED_BASE_URL: ""
    volumes:
      - ./data/pre_medications:/app/data
